[project]
site_name = "ASIX"
site_url = "https://lucabaldini.github.io/asix-web/"
site_description = "ASIX project website"
site_author = "Luca Baldini"
copyright = "&copy; 2026 the ASIX team"
docs_dir = "docs"
site_dir = "site"
extra_css = ["stylesheets/extra.css"]
nav = [
  {"Home" = "index.md"},
  {"Team" = "team.md"},
  {"Project" = "project.md"},
  {"Software" = "software.md"},
  {"Publications" = "publications.md"}
]

[project.theme]
variant = "modern"
logo = "assets/images/asix_logo.svg"
features = [
  "navigation.instant",
  "navigation.tabs",
  "navigation.top"
]
